const fs = require('fs');
const path = require('path');

const localesDir = 'frontend/assets/locales';

const translations = {
  "da": {
    "Profil mis à jour avec succès !": "Profil opdateret med succes!",
    "Erreur lors de la mise à jour du profil": "Fejl ved opdatering af profil",
    "Paramètres de sécurité mis à jour": "Sikkerhedsindstillinger opdateret",
    "Mot de passe mis à jour": "Adgangskode opdateret",
    "Code PIN mis à jour avec succès": "PIN-kode opdateret",
    "Préférences de notifications enregistrées": "Notifikationspræferencer gemt",
    "Plafonds mis à jour avec succès": "Grænser opdateret med succes",
    "Paramètres de virements mis à jour": "Overførselsindstillinger opdateret",
    "Préférences d'apparence appliquées": "Udseendepræferencer anvendt",
    "Préférences de confidentialité enregistrées": "Privatlivspræferencer gemt",
    "Notification": "Notification",
    "Succès !": "Succes!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Forkert PIN-kode. Indtast venligst den korrekte PIN-kode.",
    "Identifiants invalides": "Ugyldige legitimationsoplysninger",
    "Votre code PIN a été modifié.": "Din PIN-kode er blevet ændret.",
    "Votre mot de passe a été modifié.": "Din adgangskode er blevet ændret.",
    "Virement initié": "Overførsel startet",
    "Débit effectué": "Debitering gennemført",
    "Votre virement est en cours de validation.": "Din overførsel er under validering.",
    "Virement reçu": "Overførsel modtaget",
    "Virement validé": "Overførsel valideret",
    "Votre virement immédiat a été exécuté avec succès.": "Din straksoverførsel er blevet udført.",
    "Votre virement de {amount} a été envoyé.": "Din overførsel på {amount} er blevet sendt.",
    "Vous avez reçu un virement de {amount}.": "Du har modtaget en overførsel på {amount}."
  },
  "de": {
    "Profil mis à jour avec succès !": "Profil erfolgreich aktualisiert!",
    "Erreur lors de la mise à jour du profil": "Fehler beim Aktualisieren des Profils",
    "Paramètres de sécurité mis à jour": "Sicherheitseinstellungen aktualisiert",
    "Mot de passe mis à jour": "Passwort aktualisiert",
    "Code PIN mis à jour avec succès": "PIN-Code erfolgreich aktualisiert",
    "Préférences de notifications enregistrées": "Benachrichtigungseinstellungen gespeichert",
    "Plafonds mis à jour avec succès": "Limits erfolgreich aktualisiert",
    "Paramètres de virements mis à jour": "Überweisungseinstellungen aktualisiert",
    "Préférences d'apparence appliquées": "Erscheinungsbildeinstellungen angewendet",
    "Préférences de confidentialité enregistrées": "Datenschutzeinstellungen gespeichert",
    "Notification": "Benachrichtigung",
    "Succès !": "Erfolg!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Falscher PIN-Code. Bitte geben Sie den korrekten PIN-Code ein.",
    "Identifiants invalides": "Ungültige Anmeldedaten",
    "Votre code PIN a été modifié.": "Ihre PIN wurde geändert.",
    "Votre mot de passe a été modifié.": "Ihr Passwort wurde geändert.",
    "Virement initié": "Überweisung initiiert",
    "Débit effectué": "Belastung durchgeführt",
    "Votre virement est en cours de validation.": "Ihre Überweisung wird gerade geprüft.",
    "Virement reçu": "Überweisung erhalten",
    "Virement validé": "Überweisung bestätigt",
    "Votre virement immédiat a été exécuté avec succès.": "Ihre Echtzeitüberweisung wurde erfolgreich ausgeführt.",
    "Votre virement de {amount} a été envoyé.": "Ihre Überweisung von {amount} wurde gesendet.",
    "Vous avez reçu un virement de {amount}.": "Sie haben eine Überweisung von {amount} erhalten."
  },
  "en": {
    "Profil mis à jour avec succès !": "Profile successfully updated!",
    "Erreur lors de la mise à jour du profil": "Error updating profile",
    "Paramètres de sécurité mis à jour": "Security settings updated",
    "Mot de passe mis à jour": "Password updated",
    "Code PIN mis à jour avec succès": "PIN code successfully updated",
    "Préférences de notifications enregistrées": "Notification preferences saved",
    "Plafonds mis à jour avec succès": "Limits successfully updated",
    "Paramètres de virements mis à jour": "Transfer settings updated",
    "Préférences d'apparence appliquées": "Appearance preferences applied",
    "Préférences de confidentialité enregistrées": "Privacy preferences saved",
    "Notification": "Notification",
    "Succès !": "Success!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Incorrect PIN code. Please enter the correct PIN code.",
    "Identifiants invalides": "Invalid credentials",
    "Votre code PIN a été modifié.": "Your PIN code has been modified.",
    "Votre mot de passe a été modifié.": "Your password has been modified.",
    "Virement initié": "Transfer initiated",
    "Débit effectué": "Debit successful",
    "Votre virement est en cours de validation.": "Your transfer is being validated.",
    "Virement reçu": "Transfer received",
    "Virement validé": "Transfer validated",
    "Votre virement immédiat a été exécuté avec succès.": "Your immediate transfer has been successfully executed.",
    "Votre virement de {amount} a été envoyé.": "Your transfer of {amount} has been sent.",
    "Vous avez reçu un virement de {amount}.": "You have received a transfer of {amount}."
  },
  "es": {
    "Profil mis à jour avec succès !": "¡Perfil actualizado con éxito!",
    "Erreur lors de la mise à jour du profil": "Error al actualizar el perfil",
    "Paramètres de sécurité mis à jour": "Configuración de seguridad actualizada",
    "Mot de passe mis à jour": "Contraseña actualizada",
    "Code PIN mis à jour avec succès": "Código PIN actualizado con éxito",
    "Préférences de notifications enregistrées": "Preferencias de notificación guardadas",
    "Plafonds mis à jour avec succès": "Límites actualizados con éxito",
    "Paramètres de virements mis à jour": "Configuración de transferencias actualizada",
    "Préférences d'apparence appliquées": "Preferencias de apariencia aplicadas",
    "Préférences de confidentialité enregistrées": "Preferencias de privacidad guardadas",
    "Notification": "Notificación",
    "Succès !": "¡Éxito!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Código PIN incorrecto. Por favor, introduzca el código PIN correcto.",
    "Identifiants invalides": "Credenciales inválidas",
    "Votre code PIN a été modifié.": "Su código PIN ha sido modificado.",
    "Votre mot de passe a été modifié.": "Su contraseña ha sido modificada.",
    "Virement initié": "Transferencia iniciada",
    "Débit effectué": "Débito realizado",
    "Votre virement est en cours de validation.": "Su transferencia está siendo validada.",
    "Virement reçu": "Transferencia recibida",
    "Virement validé": "Transferencia validada",
    "Votre virement immédiat a été exécuté avec succès.": "Su transferencia inmediata se ha ejecutado con éxito.",
    "Votre virement de {amount} a été envoyé.": "Su transferencia de {amount} ha sido enviada.",
    "Vous avez reçu un virement de {amount}.": "Ha recibido una transferencia de {amount}."
  },
  "fr": {
    "Profil mis à jour avec succès !": "Profil mis à jour avec succès !",
    "Erreur lors de la mise à jour du profil": "Erreur lors de la mise à jour du profil",
    "Paramètres de sécurité mis à jour": "Paramètres de sécurité mis à jour",
    "Mot de passe mis à jour": "Mot de passe mis à jour",
    "Code PIN mis à jour avec succès": "Code PIN mis à jour avec succès",
    "Préférences de notifications enregistrées": "Préférences de notifications enregistrées",
    "Plafonds mis à jour avec succès": "Plafonds mis à jour avec succès",
    "Paramètres de virements mis à jour": "Paramètres de virements mis à jour",
    "Préférences d'apparence appliquées": "Préférences d'apparence appliquées",
    "Préférences de confidentialité enregistrées": "Préférences de confidentialité enregistrées",
    "Notification": "Notification",
    "Succès !": "Succès !",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Code PIN erroné. Veuillez entrer le bon code PIN.",
    "Identifiants invalides": "Identifiants invalides",
    "Votre code PIN a été modifié.": "Votre code PIN a été modifié.",
    "Votre mot de passe a été modifié.": "Votre mot de passe a été modifié.",
    "Virement initié": "Virement initié",
    "Débit effectué": "Débit effectué",
    "Votre virement est en cours de validation.": "Votre virement est en cours de validation.",
    "Virement reçu": "Virement reçu",
    "Virement validé": "Virement validé",
    "Votre virement immédiat a été exécuté avec succès.": "Votre virement immédiat a été exécuté avec succès.",
    "Votre virement de {amount} a été envoyé.": "Votre virement de {amount} a été envoyé.",
    "Vous avez reçu un virement de {amount}.": "Vous avez reçu un virement de {amount}."
  },
  "hr": {
    "Profil mis à jour avec succès !": "Profil uspješno ažuriran!",
    "Erreur lors de la mise à jour du profil": "Pogreška pri ažuriranju profila",
    "Paramètres de sécurité mis à jour": "Sigurnosne postavke ažurirane",
    "Mot de passe mis à jour": "Lozinka ažurirana",
    "Code PIN mis à jour avec succès": "PIN kod uspješno ažuriran",
    "Préférences de notifications enregistrées": "Postavke obavijesti spremljene",
    "Plafonds mis à jour avec succès": "Ograničenja uspješno ažurirana",
    "Paramètres de virements mis à jour": "Postavke prijenosa ažurirane",
    "Préférences d'apparence appliquées": "Postavke izgleda primijenjene",
    "Préférences de confidentialité enregistrées": "Postavke privatnosti spremljene",
    "Notification": "Obavijest",
    "Succès !": "Uspjeh!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Netočan PIN kod. Molimo unesite ispravan PIN kod.",
    "Identifiants invalides": "Nevažeće vjerodajnice",
    "Votre code PIN a été modifié.": "Vaš PIN kod je promijenjen.",
    "Votre mot de passe a été modifié.": "Vaša lozinka je promijenjena.",
    "Virement initié": "Prijenos iniciran",
    "Débit effectué": "Zaduženje izvršeno",
    "Votre virement est en cours de validation.": "Vaš prijenos je u postupku provjere.",
    "Virement reçu": "Prijenos primljen",
    "Virement validé": "Prijenos potvrđen",
    "Votre virement immédiat a été exécuté avec succès.": "Vaš trenutni prijenos uspješno je izvršen.",
    "Votre virement de {amount} a été envoyé.": "Vaš prijenos od {amount} je poslan.",
    "Vous avez reçu un virement de {amount}.": "Dobili ste prijenos od {amount}."
  },
  "hu": {
    "Profil mis à jour avec succès !": "A profil sikeresen frissítve!",
    "Erreur lors de la mise à jour du profil": "Hiba történt a profil frissítésekor",
    "Paramètres de sécurité mis à jour": "Biztonsági beállítások frissítve",
    "Mot de passe mis à jour": "Jelszó frissítve",
    "Code PIN mis à jour avec succès": "PIN kód sikeresen frissítve",
    "Préférences de notifications enregistrées": "Értesítési beállítások mentve",
    "Plafonds mis à jour avec succès": "Limitek sikeresen frissítve",
    "Paramètres de virements mis à jour": "Átutalási beállítások frissítve",
    "Préférences d'apparence appliquées": "Megjelenési beállítások alkalmazva",
    "Préférences de confidentialité enregistrées": "Adatvédelmi beállítások mentve",
    "Notification": "Értesítés",
    "Succès !": "Siker!",
    "Code PIN erroné. Veuillez entrer le bon code PIN.": "Helytelen PIN-kód. Kérjük, adja meg a helyes PIN-kódot.",
    "Identifiants invalides": "Érvénytelen hitelesítő adatok",
    "Votre code PIN a été modifié.": "A PIN kódja megváltozott.",
    "Votre mot de passe a été modifié.": "A jelszava megváltozott.",
    "Virement initié": "Átutalás elindítva",
    "Débit effectué": "Terhelés sikeres",
    "Votre virement est en cours de validation.": "Az átutalása ellenőrzés alatt áll.",
    "Virement reçu": "Átutalás érkezett",
    "Virement validé": "Átutalás jóváhagyva",
    "Votre virement immédiat a été exécuté avec succès.": "Az azonnali átutalás sikeresen végrehajtva.",
    "Votre virement de {amount} a été envoyé.": "A(z) {amount} összegű átutalása elküldve.",
    "Vous avez reçu un virement de {amount}.": "Ön egy {amount} összegű átutalást kapott."
  }
};

fs.readdirSync(localesDir).forEach(file => {
  if (file.endsWith('.json')) {
    const langCode = path.basename(file, '.json');
    if (translations[langCode]) {
      const filePath = path.join(localesDir, file);
      let json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      
      // Inject translations
      Object.assign(json, translations[langCode]);
      
      fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
      console.log(`Directly updated ${file}`);
    }
  }
});
