const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, 'frontend', 'assets', 'locales');
const langs = ['en', 'es', 'de', 'da', 'hu', 'hr'];

const enTranslations = {
  "Aide & Support": "Help & Support",
  "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "Need help? Our team is at your disposal by email or via Live Chat.",
  "Profil & identité": "Profile & identity",
  "Sécurité": "Security",
  "Notifications": "Notifications",
  "Cartes & plafonds": "Cards & limits",
  "Virements": "Transfers",
  "Apparence": "Appearance",
  "Abonnement": "Subscription",
  "Confidentialité": "Privacy",
  "Se déconnecter": "Logout",
  "Supprimer le compte": "Delete account",
  "Gérez vos informations personnelles et de contact": "Manage your personal and contact information",
  "Annuler": "Cancel",
  "Enregistrer": "Save",
  "Informations personnelles": "Personal information",
  "Votre identité telle qu'elle apparaît sur votre compte": "Your identity as it appears on your account",
  "MR": "MR",
  "Modifier": "Edit",
  "Prénom": "First name",
  "Nom": "Last name",
  "Date de naissance": "Date of birth",
  "Nationalité": "Nationality",
  "Adresse": "Address",
  "Contact": "Contact",
  "Email et téléphone associés au compte": "Email and phone associated with the account",
  "Adresse email": "Email address",
  "Téléphone": "Phone",
  "Protégez l'accès à votre compte": "Protect access to your account",
  "Mot de passe": "Password",
  "Modifiez votre mot de passe de connexion": "Change your login password",
  "Mot de passe actuel": "Current password",
  "Nouveau mot de passe": "New password",
  "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Strong • Min. 8 chars, 1 uppercase, 1 number",
  "Confirmer le nouveau mot de passe": "Confirm new password",
  "Mettre à jour le mot de passe": "Update password",
  "Double authentification (2FA)": "Two-factor authentication (2FA)",
  "Sécurité supplémentaire pour la connexion": "Extra security for login",
  "SMS OTP": "SMS OTP",
  "Email OTP": "Email OTP",
  "Contrôlez les alertes que vous recevez": "Control the alerts you receive",
  "Alertes de transaction": "Transaction alerts",
  "Soyez notifié à chaque mouvement": "Be notified of every movement",
  "Virements reçus": "Transfers received",
  "Notification push & Email": "Push notification & Email",
  "Virements émis": "Transfers sent",
  "Notification push uniquement": "Push notification only",
  "Paiements par carte refusés": "Declined card payments",
  "Alerte immédiate par SMS": "Immediate SMS alert",
  "Alertes de sécurité": "Security alerts",
  "Surveillance de l'activité du compte": "Account activity monitoring",
  "Nouvelles connexions": "New logins",
  "Alerte sur les nouveaux appareils": "Alert on new devices",
  "Changement de mot de passe": "Password change",
  "Requis par défaut": "Required by default",
  "Gérez vos cartes bancaires et limites": "Manage your bank cards and limits",
  "Ma Carte Fintechia": "My Fintechia Card",
  "Paiement sans contact": "Contactless payment",
  "Paiements à l'étranger": "Payments abroad",
  "Bloquer la carte": "Block card",
  "Plafonds sur 30 jours": "30-day limits",
  "Modifiable": "Modifiable",
  "Gérez vos bénéficiaires et limites de transferts": "Manage your beneficiaries and transfer limits",
  "Plafonds de virements": "Transfer limits",
  "Sécurité anti-fraude": "Anti-fraud security",
  "Plafond journalier (Virements SEPA)": "Daily limit (SEPA transfers)",
  "Validation forte requise au-delà de": "Strong validation required above",
  "Toutes les transactions": "All transactions",
  "Personnalisez l'interface": "Customize interface",
  "Thème de l'application": "App theme",
  "Mode clair ou sombre": "Light or dark mode",
  "Mode Clair": "Light Mode",
  "Mode Sombre": "Dark Mode",
  "Votre forfait actuel et factures": "Your current plan and invoices",
  "Plan Standard": "Standard Plan",
  "Inclus toutes les opérations courantes": "Includes all standard operations",
  "Découvrir l'offre Premium": "Discover the Premium offer",
  "Contrôle de vos données": "Control over your data",
  "Utilisation des données": "Data usage",
  "Consentements RGPD": "GDPR Consents",
  "Offres personnalisées": "Personalized offers",
  "Autoriser l'analyse pour des offres ciblées": "Allow analysis for targeted offers",
  "Partage avec des partenaires": "Share with partners",
  "Services tiers": "Third-party services",
  "Paramètres": "Settings",
  "Crédit": "Credit",
  "Crédits": "Credits"
};

const fullDict = {
  da: {
    "Aide & Support": "Hjælp og Support",
    "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "Brug for hjælp? Vores team står til din rådighed via e-mail eller Live Chat.",
    "Profil & identité": "Profil & identitet",
    "Sécurité": "Sikkerhed",
    "Notifications": "Meddelelser",
    "Cartes & plafonds": "Kort & grænser",
    "Virements": "Overførsler",
    "Apparence": "Udseende",
    "Abonnement": "Abonnement",
    "Confidentialité": "Privatliv",
    "Se déconnecter": "Log af",
    "Supprimer le compte": "Slet konto",
    "Gérez vos informations personnelles et de contact": "Administrer dine personlige og kontaktoplysninger",
    "Annuler": "Annuller",
    "Enregistrer": "Gem",
    "Informations personnelles": "Personlige oplysninger",
    "Votre identité telle qu'elle apparaît sur votre compte": "Din identitet som den vises på din konto",
    "Modifier": "Rediger",
    "Prénom": "Fornavn",
    "Nom": "Efternavn",
    "Date de naissance": "Fødselsdato",
    "Nationalité": "Nationalitet",
    "Adresse": "Adresse",
    "Contact": "Kontakt",
    "Email et téléphone associés au compte": "E-mail og telefon tilknyttet kontoen",
    "Adresse email": "E-mailadresse",
    "Téléphone": "Telefon",
    "Protégez l'accès à votre compte": "Beskyt adgangen til din konto",
    "Mot de passe": "Adgangskode",
    "Modifiez votre mot de passe de connexion": "Skift din login-adgangskode",
    "Mot de passe actuel": "Nuværende adgangskode",
    "Nouveau mot de passe": "Ny adgangskode",
    "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Stærk • Min. 8 tegn, 1 stor bogstav, 1 tal",
    "Confirmer le nouveau mot de passe": "Bekræft ny adgangskode",
    "Mettre à jour le mot de passe": "Opdater adgangskode",
    "Double authentification (2FA)": "Tofaktor-godkendelse (2FA)",
    "Sécurité supplémentaire pour la connexion": "Ekstra sikkerhed for login",
    "Contrôlez les alertes que vous recevez": "Styr de alarmer, du modtager",
    "Alertes de transaction": "Transaktionsalarmer",
    "Soyez notifié à chaque mouvement": "Bliv underrettet om hver bevægelse",
    "Virements reçus": "Modtagne overførsler",
    "Notification push & Email": "Push-meddelelse & E-mail",
    "Virements émis": "Sendte overførsler",
    "Notification push uniquement": "Kun push-meddelelse",
    "Paiements par carte refusés": "Afviste kortbetalinger",
    "Alerte immédiate par SMS": "Øjeblikkelig SMS-alarm",
    "Alertes de sécurité": "Sikkerhedsalarmer",
    "Surveillance de l'activité du compte": "Overvågning af kontoaktivitet",
    "Nouvelles connexions": "Nye logins",
    "Alerte sur les nouveaux appareils": "Alarm ved nye enheder",
    "Changement de mot de passe": "Ændring af adgangskode",
    "Requis par défaut": "Kræves som standard",
    "Gérez vos cartes bancaires et limites": "Administrer dine bankkort og grænser",
    "Ma Carte Fintechia": "Mit Fintechia-kort",
    "Paiement sans contact": "Kontaktløs betaling",
    "Paiements à l'étranger": "Betalinger i udlandet",
    "Bloquer la carte": "Bloker kort",
    "Plafonds sur 30 jours": "30-dages grænser",
    "Modifiable": "Kan ændres",
    "Gérez vos bénéficiaires et limites de transferts": "Administrer dine modtagere og overførselsgrænser",
    "Plafonds de virements": "Overførselsgrænser",
    "Sécurité anti-fraude": "Antisvindelsikkerhed",
    "Plafond journalier (Virements SEPA)": "Daglig grænse (SEPA-overførsler)",
    "Validation forte requise au-delà de": "Stærk godkendelse påkrævet over",
    "Toutes les transactions": "Alle transaktioner",
    "Personnalisez l'interface": "Tilpas grænsefladen",
    "Thème de l'application": "App-tema",
    "Mode clair ou sombre": "Lys eller mørk tilstand",
    "Mode Clair": "Lys tilstand",
    "Mode Sombre": "Mørk tilstand",
    "Votre forfait actuel et factures": "Dit nuværende abonnement og fakturaer",
    "Plan Standard": "Standardabonnement",
    "Inclus toutes les opérations courantes": "Inkluderer alle standardoperationer",
    "Découvrir l'offre Premium": "Opdag Premium-tilbuddet",
    "Contrôle de vos données": "Kontrol over dine data",
    "Utilisation des données": "Databrug",
    "Consentements RGPD": "GDPR-samtykker",
    "Offres personnalisées": "Personlige tilbud",
    "Autoriser l'analyse pour des offres ciblées": "Tillad analyse til målrettede tilbud",
    "Partage avec des partenaires": "Del med partnere",
    "Services tiers": "Tredjepartstjenester",
    "Paramètres": "Indstillinger",
    "Crédit": "Kredit",
    "Crédits": "Kreditter"
  },
  hu: {
    "Aide & Support": "Súgó és Támogatás",
    "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "Segítségre van szüksége? Csapatunk rendelkezésére áll e-mailben vagy élő chaten.",
    "Profil & identité": "Profil és személyazonosság",
    "Sécurité": "Biztonság",
    "Notifications": "Értesítések",
    "Cartes & plafonds": "Kártyák és limitek",
    "Virements": "Átutalások",
    "Apparence": "Megjelenés",
    "Abonnement": "Előfizetés",
    "Confidentialité": "Adatvédelem",
    "Se déconnecter": "Kijelentkezés",
    "Supprimer le compte": "Fiók törlése",
    "Gérez vos informations personnelles et de contact": "Kezelje személyes és kapcsolattartási adatait",
    "Annuler": "Mégse",
    "Enregistrer": "Mentés",
    "Informations personnelles": "Személyes adatok",
    "Votre identité telle qu'elle apparaît sur votre compte": "Személyazonossága, ahogy a fiókjában megjelenik",
    "Modifier": "Szerkesztés",
    "Prénom": "Keresztnév",
    "Nom": "Vezetéknév",
    "Date de naissance": "Születési dátum",
    "Nationalité": "Állampolgárság",
    "Adresse": "Cím",
    "Contact": "Kapcsolat",
    "Email et téléphone associés au compte": "A fiókhoz társított e-mail és telefon",
    "Adresse email": "E-mail cím",
    "Téléphone": "Telefon",
    "Protégez l'accès à votre compte": "Védje fiókja hozzáférését",
    "Mot de passe": "Jelszó",
    "Modifiez votre mot de passe de connexion": "Módosítsa bejelentkezési jelszavát",
    "Mot de passe actuel": "Jelenlegi jelszó",
    "Nouveau mot de passe": "Új jelszó",
    "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Erős • Min. 8 kar., 1 nagybetű, 1 szám",
    "Confirmer le nouveau mot de passe": "Új jelszó megerősítése",
    "Mettre à jour le mot de passe": "Jelszó frissítése",
    "Double authentification (2FA)": "Kétfaktoros hitelesítés (2FA)",
    "Sécurité supplémentaire pour la connexion": "Extra biztonság a bejelentkezéshez",
    "Contrôlez les alertes que vous recevez": "Szabályozza a kapott riasztásokat",
    "Alertes de transaction": "Tranzakciós riasztások",
    "Soyez notifié à chaque mouvement": "Értesüljön minden mozgásról",
    "Virements reçus": "Kapott átutalások",
    "Notification push & Email": "Push értesítés és e-mail",
    "Virements émis": "Elküldött átutalások",
    "Notification push uniquement": "Csak push értesítés",
    "Paiements par carte refusés": "Elutasított kártyás fizetések",
    "Alerte immédiate par SMS": "Azonnali SMS riasztás",
    "Alertes de sécurité": "Biztonsági riasztások",
    "Surveillance de l'activité du compte": "Fiókaktivitás figyelése",
    "Nouvelles connexions": "Új bejelentkezések",
    "Alerte sur les nouveaux appareils": "Riasztás új eszközökön",
    "Changement de mot de passe": "Jelszóváltoztatás",
    "Requis par défaut": "Alapértelmezés szerint szükséges",
    "Gérez vos cartes bancaires et limites": "Kezelje bankkártyáit és limitjeit",
    "Ma Carte Fintechia": "Fintechia kártyám",
    "Paiement sans contact": "Érintés nélküli fizetés",
    "Paiements à l'étranger": "Külföldi fizetések",
    "Bloquer la carte": "Kártya letiltása",
    "Plafonds sur 30 jours": "30 napos limitek",
    "Modifiable": "Módosítható",
    "Gérez vos bénéficiaires et limites de transferts": "Kezelje kedvezményezettjeit és átutalási limitjeit",
    "Plafonds de virements": "Átutalási limitek",
    "Sécurité anti-fraude": "Csalás elleni biztonság",
    "Plafond journalier (Virements SEPA)": "Napi limit (SEPA átutalások)",
    "Validation forte requise au-delà de": "Erős hitelesítés szükséges e felett",
    "Toutes les transactions": "Minden tranzakció",
    "Personnalisez l'interface": "Felület testreszabása",
    "Thème de l'application": "Alkalmazás témája",
    "Mode clair ou sombre": "Világos vagy sötét mód",
    "Mode Clair": "Világos mód",
    "Mode Sombre": "Sötét mód",
    "Votre forfait actuel et factures": "Jelenlegi csomagja és számlái",
    "Plan Standard": "Standard csomag",
    "Inclus toutes les opérations courantes": "Minden alapvető műveletet tartalmaz",
    "Découvrir l'offre Premium": "Fedezze fel a Prémium ajánlatot",
    "Contrôle de vos données": "Az adatai feletti irányítás",
    "Utilisation des données": "Adathasználat",
    "Consentements RGPD": "GDPR hozzájárulások",
    "Offres personnalisées": "Személyre szabott ajánlatok",
    "Autoriser l'analyse pour des offres ciblées": "Engedélyezze az elemzést célzott ajánlatokhoz",
    "Partage avec des partenaires": "Megosztás partnerekkel",
    "Services tiers": "Harmadik féltől származó szolgáltatások",
    "Paramètres": "Beállítások",
    "Crédit": "Hitel",
    "Crédits": "Hitelek"
  },
  hr: {
    "Aide & Support": "Pomoć i podrška",
    "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "Trebate li pomoć? Naš tim vam je na raspolaganju putem e-pošte ili live chata.",
    "Profil & identité": "Profil i identitet",
    "Sécurité": "Sigurnost",
    "Notifications": "Obavijesti",
    "Cartes & plafonds": "Kartice i ograničenja",
    "Virements": "Prijenosi",
    "Apparence": "Izgled",
    "Abonnement": "Pretplata",
    "Confidentialité": "Privatnost",
    "Se déconnecter": "Odjava",
    "Supprimer le compte": "Izbriši račun",
    "Gérez vos informations personnelles et de contact": "Upravljajte osobnim i kontakt podacima",
    "Annuler": "Odustani",
    "Enregistrer": "Spremi",
    "Informations personnelles": "Osobni podaci",
    "Votre identité telle qu'elle apparaît sur votre compte": "Vaš identitet kako se prikazuje na vašem računu",
    "Modifier": "Uredi",
    "Prénom": "Ime",
    "Nom": "Prezime",
    "Date de naissance": "Datum rođenja",
    "Nationalité": "Nacionalnost",
    "Adresse": "Adresa",
    "Contact": "Kontakt",
    "Email et téléphone associés au compte": "E-pošta i telefon povezani s računom",
    "Adresse email": "Adresa e-pošte",
    "Téléphone": "Telefon",
    "Protégez l'accès à votre compte": "Zaštitite pristup svom računu",
    "Mot de passe": "Lozinka",
    "Modifiez votre mot de passe de connexion": "Promijenite lozinku za prijavu",
    "Mot de passe actuel": "Trenutna lozinka",
    "Nouveau mot de passe": "Nova lozinka",
    "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Jaka • Min. 8 znakova, 1 veliko, 1 broj",
    "Confirmer le nouveau mot de passe": "Potvrdite novu lozinku",
    "Mettre à jour le mot de passe": "Ažuriraj lozinku",
    "Double authentification (2FA)": "Dvostruka provjera autentičnosti (2FA)",
    "Sécurité supplémentaire pour la connexion": "Dodatna sigurnost za prijavu",
    "Contrôlez les alertes que vous recevez": "Kontrolirajte upozorenja koja primate",
    "Alertes de transaction": "Upozorenja o transakcijama",
    "Soyez notifié à chaque mouvement": "Budite obaviješteni o svakom pokretu",
    "Virements reçus": "Primljeni prijenosi",
    "Notification push & Email": "Push obavijest i e-pošta",
    "Virements émis": "Poslani prijenosi",
    "Notification push uniquement": "Samo push obavijest",
    "Paiements par carte refusés": "Odbijena plaćanja karticom",
    "Alerte immédiate par SMS": "Trenutno SMS upozorenje",
    "Alertes de sécurité": "Sigurnosna upozorenja",
    "Surveillance de l'activité du compte": "Nadzor aktivnosti računa",
    "Nouvelles connexions": "Nove prijave",
    "Alerte sur les nouveaux appareils": "Upozorenje na novim uređajima",
    "Changement de mot de passe": "Promjena lozinke",
    "Requis par défaut": "Zadano potrebno",
    "Gérez vos cartes bancaires et limites": "Upravljajte svojim bankovnim karticama i limitima",
    "Ma Carte Fintechia": "Moja Fintechia kartica",
    "Paiement sans contact": "Beskontaktno plaćanje",
    "Paiements à l'étranger": "Plaćanja u inozemstvu",
    "Bloquer la carte": "Blokiraj karticu",
    "Plafonds sur 30 jours": "30-dnevna ograničenja",
    "Modifiable": "Izmjenjivo",
    "Gérez vos bénéficiaires et limites de transferts": "Upravljajte korisnicima i ograničenjima prijenosa",
    "Plafonds de virements": "Ograničenja prijenosa",
    "Sécurité anti-fraude": "Zaštita od prijevara",
    "Plafond journalier (Virements SEPA)": "Dnevni limit (SEPA prijenosi)",
    "Validation forte requise au-delà de": "Jaka provjera potrebna iznad",
    "Toutes les transactions": "Sve transakcije",
    "Personnalisez l'interface": "Prilagodite sučelje",
    "Thème de l'application": "Tema aplikacije",
    "Mode clair ou sombre": "Svijetli ili tamni način",
    "Mode Clair": "Svijetli način",
    "Mode Sombre": "Tamni način",
    "Votre forfait actuel et factures": "Vaš trenutni plan i računi",
    "Plan Standard": "Standardni plan",
    "Inclus toutes les opérations courantes": "Uključuje sve standardne operacije",
    "Découvrir l'offre Premium": "Otkrijte Premium ponudu",
    "Contrôle de vos données": "Kontrola nad vašim podacima",
    "Utilisation des données": "Korištenje podataka",
    "Consentements RGPD": "GDPR pristanci",
    "Offres personnalisées": "Personalizirane ponude",
    "Autoriser l'analyse pour des offres ciblées": "Dozvoli analizu za ciljane ponude",
    "Partage avec des partenaires": "Dijeli s partnerima",
    "Services tiers": "Usluge trećih strana",
    "Paramètres": "Postavke",
    "Crédit": "Kredit",
    "Crédits": "Krediti"
  },
  es: {
    "Aide & Support": "Ayuda y Soporte",
    "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "¿Necesitas ayuda? Nuestro equipo está a tu disposición por correo electrónico o a través de Live Chat.",
    "Profil & identité": "Perfil e identidad",
    "Sécurité": "Seguridad",
    "Notifications": "Notificaciones",
    "Cartes & plafonds": "Tarjetas y límites",
    "Virements": "Transferencias",
    "Apparence": "Apariencia",
    "Abonnement": "Suscripción",
    "Confidentialité": "Privacidad",
    "Se déconnecter": "Cerrar sesión",
    "Supprimer le compte": "Eliminar cuenta",
    "Gérez vos informations personnelles et de contact": "Gestiona tu información personal y de contacto",
    "Annuler": "Cancelar",
    "Enregistrer": "Guardar",
    "Informations personnelles": "Información personal",
    "Votre identité telle qu'elle apparaît sur votre compte": "Tu identidad tal como aparece en tu cuenta",
    "Modifier": "Editar",
    "Prénom": "Nombre",
    "Nom": "Apellido",
    "Date de naissance": "Fecha de nacimiento",
    "Nationalité": "Nacionalidad",
    "Adresse": "Dirección",
    "Contact": "Contacto",
    "Email et téléphone associés au compte": "Correo electrónico y teléfono asociados a la cuenta",
    "Adresse email": "Dirección de correo electrónico",
    "Téléphone": "Teléfono",
    "Protégez l'accès à votre compte": "Protege el acceso a tu cuenta",
    "Mot de passe": "Contraseña",
    "Modifiez votre mot de passe de connexion": "Cambia tu contraseña de inicio de sesión",
    "Mot de passe actuel": "Contraseña actual",
    "Nouveau mot de passe": "Nueva contraseña",
    "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Fuerte • Mín. 8 caract., 1 mayúsc., 1 número",
    "Confirmer le nouveau mot de passe": "Confirmar la nueva contraseña",
    "Mettre à jour le mot de passe": "Actualizar contraseña",
    "Double authentification (2FA)": "Autenticación de dos factores (2FA)",
    "Sécurité supplémentaire pour la connexion": "Seguridad adicional para el inicio de sesión",
    "Contrôlez les alertes que vous recevez": "Controla las alertas que recibes",
    "Alertes de transaction": "Alertas de transacciones",
    "Soyez notifié à chaque mouvement": "Sé notificado de cada movimiento",
    "Virements reçus": "Transferencias recibidas",
    "Notification push & Email": "Notificación push y correo",
    "Virements émis": "Transferencias enviadas",
    "Notification push uniquement": "Solo notificación push",
    "Paiements par carte refusés": "Pagos con tarjeta rechazados",
    "Alerte immédiate par SMS": "Alerta SMS inmediata",
    "Alertes de sécurité": "Alertas de seguridad",
    "Surveillance de l'activité du compte": "Monitoreo de la actividad de la cuenta",
    "Nouvelles connexions": "Nuevos inicios de sesión",
    "Alerte sur les nouveaux appareils": "Alerta sobre nuevos dispositivos",
    "Changement de mot de passe": "Cambio de contraseña",
    "Requis par défaut": "Requerido por defecto",
    "Gérez vos cartes bancaires et limites": "Gestiona tus tarjetas bancarias y límites",
    "Ma Carte Fintechia": "Mi Tarjeta Fintechia",
    "Paiement sans contact": "Pago sin contacto",
    "Paiements à l'étranger": "Pagos en el extranjero",
    "Bloquer la carte": "Bloquear tarjeta",
    "Plafonds sur 30 jours": "Límites de 30 días",
    "Modifiable": "Modificable",
    "Gérez vos bénéficiaires et limites de transferts": "Gestiona tus beneficiarios y límites de transferencias",
    "Plafonds de virements": "Límites de transferencias",
    "Sécurité anti-fraude": "Seguridad antifraude",
    "Plafond journalier (Virements SEPA)": "Límite diario (Transferencias SEPA)",
    "Validation forte requise au-delà de": "Autenticación fuerte requerida por encima de",
    "Toutes les transactions": "Todas las transacciones",
    "Personnalisez l'interface": "Personalizar la interfaz",
    "Thème de l'application": "Tema de la aplicación",
    "Mode clair ou sombre": "Modo claro o oscuro",
    "Mode Clair": "Modo Claro",
    "Mode Sombre": "Modo Oscuro",
    "Votre forfait actuel et factures": "Tu plan actual y facturas",
    "Plan Standard": "Plan Estándar",
    "Inclus toutes les opérations courantes": "Incluye todas las operaciones estándar",
    "Découvrir l'offre Premium": "Descubre la oferta Premium",
    "Contrôle de vos données": "Control sobre tus datos",
    "Utilisation des données": "Uso de datos",
    "Consentements RGPD": "Consentimientos RGPD",
    "Offres personnalisées": "Ofertas personalizadas",
    "Autoriser l'analyse pour des offres ciblées": "Permitir análisis para ofertas dirigidas",
    "Partage avec des partenaires": "Compartir con socios",
    "Services tiers": "Servicios de terceros",
    "Paramètres": "Configuración",
    "Crédit": "Crédito",
    "Crédits": "Créditos"
  },
  de: {
    "Aide & Support": "Hilfe & Support",
    "Besoin d'aide ? Notre équipe est à votre disposition par e-mail ou via le Chat en direct.": "Brauchen Sie Hilfe? Unser Team steht Ihnen per E-Mail oder Live-Chat zur Verfügung.",
    "Profil & identité": "Profil & Identität",
    "Sécurité": "Sicherheit",
    "Notifications": "Benachrichtigungen",
    "Cartes & plafonds": "Karten & Limits",
    "Virements": "Überweisungen",
    "Apparence": "Erscheinungsbild",
    "Abonnement": "Abonnement",
    "Confidentialité": "Datenschutz",
    "Se déconnecter": "Abmelden",
    "Supprimer le compte": "Konto löschen",
    "Gérez vos informations personnelles et de contact": "Verwalten Sie Ihre persönlichen und Kontaktinformationen",
    "Annuler": "Abbrechen",
    "Enregistrer": "Speichern",
    "Informations personnelles": "Persönliche Informationen",
    "Votre identité telle qu'elle apparaît sur votre compte": "Ihre Identität, wie sie in Ihrem Konto erscheint",
    "Modifier": "Bearbeiten",
    "Prénom": "Vorname",
    "Nom": "Nachname",
    "Date de naissance": "Geburtsdatum",
    "Nationalité": "Nationalität",
    "Adresse": "Adresse",
    "Contact": "Kontakt",
    "Email et téléphone associés au compte": "E-Mail und Telefon mit dem Konto verknüpft",
    "Adresse email": "E-Mail-Adresse",
    "Téléphone": "Telefon",
    "Protégez l'accès à votre compte": "Schützen Sie den Zugang zu Ihrem Konto",
    "Mot de passe": "Passwort",
    "Modifiez votre mot de passe de connexion": "Ändern Sie Ihr Anmeldepasswort",
    "Mot de passe actuel": "Aktuelles Passwort",
    "Nouveau mot de passe": "Neues Passwort",
    "Fort • Min. 8 caractères, 1 maj, 1 chiffre": "Stark • Min. 8 Zeichen, 1 Großbuchstabe, 1 Zahl",
    "Confirmer le nouveau mot de passe": "Neues Passwort bestätigen",
    "Mettre à jour le mot de passe": "Passwort aktualisieren",
    "Double authentification (2FA)": "Zwei-Faktor-Authentifizierung (2FA)",
    "Sécurité supplémentaire pour la connexion": "Zusätzliche Sicherheit für die Anmeldung",
    "Contrôlez les alertes que vous recevez": "Kontrollieren Sie die Alarme, die Sie erhalten",
    "Alertes de transaction": "Transaktionsalarme",
    "Soyez notifié à chaque mouvement": "Lassen Sie sich über jede Bewegung benachrichtigen",
    "Virements reçus": "Erhaltene Überweisungen",
    "Notification push & Email": "Push-Benachrichtigung & E-Mail",
    "Virements émis": "Gesendete Überweisungen",
    "Notification push uniquement": "Nur Push-Benachrichtigung",
    "Paiements par carte refusés": "Abgelehnte Kartenzahlungen",
    "Alerte immédiate par SMS": "Sofortiger SMS-Alarm",
    "Alertes de sécurité": "Sicherheitsalarme",
    "Surveillance de l'activité du compte": "Überwachung der Kontoaktivität",
    "Nouvelles connexions": "Neue Anmeldungen",
    "Alerte sur les nouveaux appareils": "Alarm bei neuen Geräten",
    "Changement de mot de passe": "Passwortänderung",
    "Requis par défaut": "Standardmäßig erforderlich",
    "Gérez vos cartes bancaires et limites": "Verwalten Sie Ihre Bankkarten und Limits",
    "Ma Carte Fintechia": "Meine Fintechia-Karte",
    "Paiement sans contact": "Kontaktloses Bezahlen",
    "Paiements à l'étranger": "Zahlungen im Ausland",
    "Bloquer la carte": "Karte sperren",
    "Plafonds sur 30 jours": "30-Tage-Limits",
    "Modifiable": "Änderbar",
    "Gérez vos bénéficiaires et limites de transferts": "Verwalten Sie Ihre Begünstigten und Überweisungslimits",
    "Plafonds de virements": "Überweisungslimits",
    "Sécurité anti-fraude": "Anti-Betrugs-Sicherheit",
    "Plafond journalier (Virements SEPA)": "Tageslimit (SEPA-Überweisungen)",
    "Validation forte requise au-delà de": "Starke Authentifizierung erforderlich über",
    "Toutes les transactions": "Alle Transaktionen",
    "Personnalisez l'interface": "Benutzeroberfläche anpassen",
    "Thème de l'application": "App-Thema",
    "Mode clair ou sombre": "Heller oder dunkler Modus",
    "Mode Clair": "Heller Modus",
    "Mode Sombre": "Dunkler Modus",
    "Votre forfait actuel et factures": "Ihr aktueller Plan und Rechnungen",
    "Plan Standard": "Standardplan",
    "Inclus toutes les opérations courantes": "Beinhaltet alle Standardoperationen",
    "Découvrir l'offre Premium": "Entdecken Sie das Premium-Angebot",
    "Contrôle de vos données": "Kontrolle über Ihre Daten",
    "Utilisation des données": "Datennutzung",
    "Consentements RGPD": "DSGVO-Zustimmungen",
    "Offres personnalisées": "Personalisierte Angebote",
    "Autoriser l'analyse pour des offres ciblées": "Analyse für gezielte Angebote zulassen",
    "Partage avec des partenaires": "Mit Partnern teilen",
    "Services tiers": "Dienste von Drittanbietern",
    "Paramètres": "Einstellungen",
    "Crédit": "Kredit",
    "Crédits": "Kredite"
  }
};

fullDict.en = enTranslations;

langs.forEach(lang => {
    const file = path.join(localesDir, `${lang}.json`);
    if (fs.existsSync(file)) {
        const dict = JSON.parse(fs.readFileSync(file, 'utf8'));
        let updated = false;
        
        Object.keys(enTranslations).forEach(key => {
            if (fullDict[lang] && fullDict[lang][key]) {
                dict[key] = fullDict[lang][key];
                updated = true;
            }
        });

        // The user also requested previous list to be proper in DA, HR, HU instead of EN fallback
        const da_fixes = {
          "Bonjour,": "Hej,", "Date du jour": "Dagens dato", "Page 1": "Side 1", "← Précédent": "← Forrige", "Suivant →": "Næste →", "Création de carte en cours": "Kortoprettelse igang", "Notre équipe finalise la configuration de votre nouvelle carte de paiement Fintechia. Vous y aurez accès dès sa validation.": "Vores team færdiggør konfigurationen af dit nye Fintechia betalingskort. Du får adgang til det, så snart det er godkendt.", "Aucune dépense récente.": "Ingen nylige udgifter.", "Nom": "Navn", "IBAN": "IBAN", "Action": "Handling", "mois d'historique": "måneders historik", "FORMAT": "FORMAT", "ENVOI EMAIL": "SEND E-MAIL", "Relevé —": "Kontoudtog —", "En cours": "I gang", "Date": "Dato", "Motif": "Årsag", "Montant": "Beløb", "Aucune demande de crédit pour le moment.": "Ingen kreditanmodning i øjeblikket.", "REVENUS MOIS": "MÅNEDLIG INDKOMST", "DÉPENSES MOIS": "MÅNEDLIGE UDGIFTER", "ÉPARGNE DU MOIS": "MÅNEDLIGE BESPARELSER", "vs préc.": "vs tidl.", "Obj.": "Mål", "Budget envelopes": "Budgetkuverter", "Mois": "Måned", "Accueil": "Hjem", "Virements": "Overførsler", "Cartes": "Kort", "Crédits": "Kreditter", "Budget": "Budget", "Bénéficiaires": "Modtagere", "Relevés": "Kontoudtog", "Aucun virement trouvé.": "Ingen overførsler fundet.", "Aucun bénéficiaire enregistré.": "Ingen gemte modtagere.", "Aucune dépense.": "Ingen udgifter.", "Aucune transaction récente.": "Ingen nylige transaktioner.", "Tout marquer lu": "Marker alt som læst", "Aucune notification": "Ingen meddelelser", "Détails de l'alerte": "Advarselsdetaljer", "Gérer (Détails)": "Administrer (Detaljer)", "Contacter": "Kontakt", "Rejeté": "Afvist", "Validé": "Valideret", "Incomplet": "Ufuldstændig", "Dossier soumis": "Fil indsendt"
        };
        const hu_fixes = {
          "Bonjour,": "Szia,", "Date du jour": "Mai dátum", "Page 1": "1. oldal", "← Précédent": "← Előző", "Suivant →": "Következő →", "Création de carte en cours": "Kártyakészítés folyamatban", "Notre équipe finalise la configuration de votre nouvelle carte de paiement Fintechia. Vous y aurez accès dès sa validation.": "Csapatunk véglegesíti új Fintechia fizetési kártyájának beállításait. Amint jóváhagyják, hozzáférhet.", "Aucune dépense récente.": "Nincsenek legutóbbi kiadások.", "Nom": "Név", "IBAN": "IBAN", "Action": "Művelet", "mois d'historique": "hónapos történelem", "FORMAT": "FORMÁTUM", "ENVOI EMAIL": "EMAIL KÜLDÉSE", "Relevé —": "Kivonat —", "En cours": "Folyamatban", "Date": "Dátum", "Motif": "Ok", "Montant": "Összeg", "Aucune demande de crédit pour le moment.": "Jelenleg nincs hitelkérelem.", "REVENUS MOIS": "HAVI JÖVEDELEM", "DÉPENSES MOIS": "HAVI KIADÁSOK", "ÉPARGNE DU MOIS": "HAVI MEGTAKARÍTÁS", "vs préc.": "vs előző", "Obj.": "Cél", "Budget envelopes": "Költségvetési borítékok", "Mois": "Hónap", "Accueil": "Kezdőlap", "Virements": "Átutalások", "Cartes": "Kártyák", "Crédits": "Hitelek", "Budget": "Költségvetés", "Bénéficiaires": "Kedvezményezettek", "Relevés": "Kivonatok", "Aucun virement trouvé.": "Nincs található átutalás.", "Aucun bénéficiaire enregistré.": "Nincs mentett kedvezményezett.", "Aucune dépense.": "Nincsenek kiadások.", "Aucune transaction récente.": "Nincsenek legutóbbi tranzakciók.", "Tout marquer lu": "Összes olvasottnak jelölése", "Aucune notification": "Nincsenek értesítések", "Détails de l'alerte": "Riasztás részletei", "Gérer (Détails)": "Kezelés (Részletek)", "Contacter": "Kapcsolat", "Rejeté": "Elutasítva", "Validé": "Érvényesítve", "Incomplet": "Hiányos", "Dossier soumis": "Fájl beküldve"
        };
        const hr_fixes = {
          "Bonjour,": "Bok,", "Date du jour": "Današnji datum", "Page 1": "Stranica 1", "← Précédent": "← Prethodna", "Suivant →": "Sljedeća →", "Création de carte en cours": "Izrada kartice u tijeku", "Notre équipe finalise la configuration de votre nouvelle carte de paiement Fintechia. Vous y aurez accès dès sa validation.": "Naš tim dovršava konfiguraciju vaše nove Fintechia platne kartice. Imat ćete pristup čim bude odobrena.", "Aucune dépense récente.": "Nema nedavnih troškova.", "Nom": "Ime", "IBAN": "IBAN", "Action": "Akcija", "mois d'historique": "mjeseci povijesti", "FORMAT": "FORMAT", "ENVOI EMAIL": "POŠALJI EMAIL", "Relevé —": "Izvod —", "En cours": "U tijeku", "Date": "Datum", "Motif": "Razlog", "Montant": "Iznos", "Aucune demande de crédit pour le moment.": "Trenutno nema zahtjeva za kredit.", "REVENUS MOIS": "MJESEČNI PRIHOD", "DÉPENSES MOIS": "MJESEČNI TROŠKOVI", "ÉPARGNE DU MOIS": "MJESEČNA ŠTEDNJA", "vs préc.": "vs preth.", "Obj.": "Cilj", "Budget envelopes": "Proračunske omotnice", "Mois": "Mjesec", "Accueil": "Početna", "Virements": "Prijenosi", "Cartes": "Kartice", "Crédits": "Krediti", "Budget": "Proračun", "Bénéficiaires": "Korisnici", "Relevés": "Izvodi", "Aucun virement trouvé.": "Nisu pronađeni prijenosi.", "Aucun bénéficiaire enregistré.": "Nema spremljenih korisnika.", "Aucune dépense.": "Nema troškova.", "Aucune transaction récente.": "Nema nedavnih transakcija.", "Tout marquer lu": "Označi sve kao pročitano", "Aucune notification": "Nema obavijesti", "Détails de l'alerte": "Detalji upozorenja", "Gérer (Détails)": "Upravljanje (Detalji)", "Contacter": "Kontakt", "Rejeté": "Odbijeno", "Validé": "Odobreno", "Incomplet": "Nepotpuno", "Dossier soumis": "Datoteka poslana"
        };

        if (lang === 'da') {
           Object.keys(da_fixes).forEach(k => { dict[k] = da_fixes[k]; updated = true; });
        }
        if (lang === 'hu') {
           Object.keys(hu_fixes).forEach(k => { dict[k] = hu_fixes[k]; updated = true; });
        }
        if (lang === 'hr') {
           Object.keys(hr_fixes).forEach(k => { dict[k] = hr_fixes[k]; updated = true; });
        }

        if (updated) {
            fs.writeFileSync(file, JSON.stringify(dict, null, 2));
            console.log(`Updated ${lang}.json`);
        }
    }
});
